apiVersion: v1alpha1
generated: "2018-06-20T09:05:29.280045494Z"
kind: RepositoryContent
services:
- apiVersion: v1alpha1
  metadata: 
    name: dotnet-album-viewer
  kind: Service
  spec:
    icon: https://github.com/dockersamples/dotnet-album-viewer/raw/master/src/AlbumViewerAngular/src/touch-icon.png
    description: Sample Angular (4) application demonstrating ASP.NET Core API features
    source:
      image: docker.io/magicwand/dotnet-album-viewer:v0.1.0
    options:
    - defaultValue: "8000"
      label: External port
      name: externalPort
      type: hostPort
    title: West Wind Album Viewer ASP.NET Core Sample
templates:
- apiVersion: v1alpha1
  metadata: 
    name: dotnet-album-viewer-sqlserver
  kind: Template
  spec:
    title: West Wind Album Viewer ASP.NET Core Sample
    description: Sample Angular (4) application demonstrating ASP.NET Core API features
    services:
    - name: db
      serviceId: mssql-server-linux
    - name: app
      serviceId: dotnet-album-viewer
